### PR TITLE
Fix so that DATABASE_URL can be read from the .env file

### PR DESCRIPTION
**Pull request by natecook1000**

### CODE REVIEW

**Comment by mattt** [comment]
This is automatically populated when `$ foreman start` is run, and is pre-set as an environment variable when deploying to Heroku, so this shouldn't be necessary... Are you running this some other way?

**Comment by natecook1000** [comment]
I was getting an error that the connection was nil when trying to build the database with `bundle exec rake db:seed`. Could it be my ruby version? I'm on 2.0.0p451.

**Comment by mattt** [comment]
Ah, you'd need to do `$ foreman run bundle exec rake db:seed` (a mouthful, I know).

I personally like not having that automatically defined for Rake tasks, since I actually populate the production database locally from that, passing in the `DATABASE_URL` from `$ heroku:config`

**Comment by natecook1000** [comment]
Great! I'll back this out and update the README instead.

**Comment by mattt** [comment]
:ok_hand: :grin:

**Pull request closed without merging**
